### ISSUE TITLE
Error in executing the python code: "IndexError: pop from empty list"

### ISSUE THREAD

**Issue by MagnoliaChampaca** [PratyushTripathy/COINS#4]
At the last step of the process, when the output file is to be created after typing in the deflection angle threshold, the output is interrupted by an error in 'executing the python code'. The error reads: "IndexError: pop from empty list".

How can this be fixed?

**Comment by PratyushTripathy** [comment]
@MagnoliaChampaca could you please share the exact script that you are using and the file here?

**Comment by OneDay48Hours** [comment]
I have the same issue, any solution now?

The error is as follows:

An error has occurred while executing Python code: 

IndexError: pop from empty list 
Traceback (most recent call last):
  File "/Users/a/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/coins/coins.py", line 231, in startProcessing
    self.processNetworkVector()
  File "/Users/a/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/coins/coins.py", line 243, in processNetworkVector
    myNetwork = network(inFile)
  File "/Users/a/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/coins/streetHierarchy.py", line 173, in __init__
    self.pythonPath = getPythonPath()
  File "/Users/a/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/coins/streetHierarchy.py", line 32, in getPythonPath
    path.pop()
IndexError: pop from empty list

**Comment by OneDay48Hours** [comment]
> I have the same issue, any solution now?
> 
> The error is as follows:
> 
> An error has occurred while executing Python code:
> 
> IndexError: pop from empty list Traceback (most recent call last): File "/Users/a/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/coins/coins.py", line 231, in startProcessing self.processNetworkVector() File "/Users/a/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/coins/coins.py", line 243, in processNetworkVector myNetwork = network(inFile) File "/Users/a/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/coins/streetHierarchy.py", line 173, in **init** self.pythonPath = getPythonPath() File "/Users/a/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/coins/streetHierarchy.py", line 32, in getPythonPath path.pop() IndexError: pop from empty list

Hi, I've found the reason for this error. This is due to the different path separators for different operating systems. In macOS, file paths use forward slashes / instead of backslashes \. Therefore, just modify the code to accommodate the format of macOS file paths.

Here's the modified code:
def getPythonPath():
    **path = os.__file__.split('/')**
    path.pop()
    path.pop()
    **path = '/'.join(path)**
    return path

After making these changes, the code should run without error. However, it continues to spin indefinitely without producing any results after clicking "Run", there may be another issue that needs to be investigated.

**Comment by PratyushTripathy** [comment]
Moving forward, COINS will be available and maintained under the MomePy Python package. See Momepy API here [https://docs.momepy.org/en/latest/api/momepy.COINS.html](https://docs.momepy.org/en/latest/api/momepy.COINS.html).
