### ISSUE TITLE
Get Point Count error

### ISSUE THREAD

**Issue by JohnsWillson** [PratyushTripathy/COINS#5]
while trying use the tool i am getting his error
Traceback (most recent call last):
  File "C:\Users/johns/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\coins\coins.py", line 231, in startProcessing
    self.processNetworkVector()
  File "C:\Users/johns/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\coins\coins.py", line 245, in processNetworkVector
    myNetwork.splitLines1()
  File "C:\Users/johns/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\coins\streetHierarchy.py", line 219, in splitLines1
    for lineEdge in range(geom.GetPointCount()):
AttributeError: 'NoneType' object has no attribute 'GetPointCount'
![Screenshot (250)](https://github.com/PratyushTripathy/COINS/assets/165782884/22b5e5cb-01ff-4330-afa5-01f355737564)

**Comment by PratyushTripathy** [comment]
@JohnsWillson The QGIS plugin is not longer being maintained. Please use the Momepy Python package. See API [https://docs.momepy.org/en/latest/api/momepy.COINS.html](https://docs.momepy.org/en/latest/api/momepy.COINS.html)
